### PR TITLE
v4.0.0

### PR DESCRIPTION
**Pull request by mthadley**
## Description

Includes...

* #237
* #235 

Making this a major version bump since one of the commits drop support for Python 2.

## Documentation

Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

```
[ ] Yes
```

If yes, link a related docs PR and add a docs maintainer as a reviewer. Their approval is required.

### CODE REVIEW

**Review by ameesha — APPROVED** [review]

**Comment by amygdalama** [comment]
we'll need to add session.created today too, should we wait for that? 🤔 

or we could do two releases.

**Comment by mthadley** [comment]
> we'll need to add session.created today too, should we wait for that? 🤔
> 
> or we could do two releases.

@amygdalama Do we need to make changes in this SDK to support the new event?

Maybe I'm missing it, but I didn't recall any enum equivalent in Python for event types.

**Comment by amygdalama** [comment]
oh! ok nice nvm then

**Comment by mthadley** [comment]
FYI: Making this a major version bump since one of the commits drops support for Python 2.

**Review by ameesha — APPROVED** [review]

**Review by jonatascastro12 — APPROVED** [review]
Looks good! Thanks for covering the Python 2 here @mthadley

**Pull request merged**
